version: '3.9'

services:
  taiga-back:
    image: taigaio/taiga-back:latest
    command: /usr/local/bin/gunicorn -w 4 -b 0.0.0.0:8000 taiga.wsgi:application
    environment:
      TAIGA_LANG: ${TAIGA_LANG}
      TAIGA_SECRET_KEY: ${TAIGA_SECRET_KEY}
      TAIGA_BACKEND_URL: ${TAIGA_BACKEND_URL}
      TAIGA_FRONTEND_URL: ${TAIGA_FRONTEND_URL}
      TAIGA_SUPPORT_EMAIL: ${TAIGA_SUPPORT_EMAIL}
      TAIGA_STATIC_ROOT: /taiga/static
      TAIGA_MEDIA_ROOT: /taiga/media
      TAIGA_DB_HOST: taiga-db
      TAIGA_DB_NAME: ${TAIGA_DB_NAME}
      TAIGA_DB_USER: ${TAIGA_DB_USER}
      TAIGA_DB_PASSWORD: ${TAIGA_DB_PASSWORD}
      TAIGA_GITHUB_CLIENT_ID: ${TAIGA_GITHUB_CLIENT_ID}
      TAIGA_GITHUB_CLIENT_SECRET: ${TAIGA_GITHUB_CLIENT_SECRET}
      TAIGA_GITLAB_URL: ${TAIGA_GITLAB_URL}
      TAIGA_GITLAB_CLIENT_ID: ${TAIGA_GITLAB_CLIENT_ID}
      TAIGA_GITLAB_CLIENT_SECRET: ${TAIGA_GITLAB_CLIENT_SECRET}
      TAIGA_GOOGLE_CLIENT_ID: ${TAIGA_GOOGLE_CLIENT_ID}
      TAIGA_GOOGLE_CLIENT_SECRET: ${TAIGA_GOOGLE_CLIENT_SECRET}
      TAIGA_EMAIL__BACKEND: ${TAIGA_EMAIL_BACKEND}
      TAIGA_EMAIL__DEFAULT_SENDER: ${TAIGA_EMAIL_DEFAULT_SENDER}
      TAIGA_EMAIL__SERVER: ${TAIGA_EMAIL_SERVER}
      TAIGA_EMAIL__USERNAME: ${TAIGA_EMAIL_USERNAME}
      TAIGA_EMAIL__PASSWORD: ${TAIGA_EMAIL_PASSWORD}
      TAIGA_EMAIL__PORT: ${TAIGA_EMAIL_PORT}
      TAIGA_EMAIL__USE_TLS: ${TAIGA_EMAIL_USE_TLS}
      TAIGA_EMAIL__USE_SSL: ${TAIGA_EMAIL_USE_SSL}
      TAIGA_EVENTS__REDIS_HOST: taiga-redis
    volumes:
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - taiga
    depends_on:
            taiga-db:
        condition: service_started
      taiga-redis:
        condition: service_healthy

  taiga-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${TAIGA_DB_NAME}
      POSTGRES_USER: ${TAIGA_DB_USER}
      POSTGRES_PASSWORD: ${TAIGA_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TAIGA_DB_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 15s
      retries: 5
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_BACKEND_URL: ${TAIGA_BACKEND_URL}
      TAIGA_EVENTS_URL: ${TAIGA_EVENTS_URL}
      TAIGA_SUPPORT_EMAIL: ${TAIGA_SUPPORT_EMAIL}
      TAIGA_GITHUB_CLIENT_ID: ${TAIGA_GITHUB_CLIENT_ID}
      TAIGA_GITLAB_URL: ${TAIGA_GITLAB_URL}
      TAIGA_GITLAB_CLIENT_ID: ${TAIGA_GITLAB_CLIENT_ID}
      TAIGA_GOOGLE_CLIENT_ID: ${TAIGA_GOOGLE_CLIENT_ID}
    networks:
      - taiga
    ports:
      - 9000:80
    volumes:
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    depends_on:
            taiga-back:
        condition: service_started

  taiga-worker:
    image: taigaio/taiga-back:latest
    command: celery -A taiga worker --concurrency=4
    environment:
      TAIGA_BACKEND_URL: ${TAIGA_BACKEND_URL}
      TAIGA_DB_HOST: taiga-db
      TAIGA_DB_NAME: ${TAIGA_DB_NAME}
      TAIGA_DB_USER: ${TAIGA_DB_USER}
      TAIGA_DB_PASSWORD: ${TAIGA_DB_PASSWORD}
    restart: always
    networks:
      - taiga
    depends_on:
            taiga-db:
        condition: service_started
      taiga-redis:
        condition: service_healthy

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:

networks:
  taiga:
