services:
  taiga-back:
    image: taigaio/taiga-back:latest
    command: init-and-serve
    environment:
      TAIGA_LANG: ${TAIGA_LANG}
      TAIGA_SECRET_KEY: ${TAIGA_SECRET_KEY}
      # Outras variáveis
    volumes:
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-redis:
        condition: service_healthy

  taiga-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${TAIGA_DB_NAME}
      POSTGRES_USER: ${TAIGA_DB_USER}
      POSTGRES_PASSWORD: ${TAIGA_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TAIGA_DB_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 15s
      retries: 5
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest  # Corrigido o nome da imagem
    environment:
      TAIGA_BACKEND_URL: ${TAIGA_BACKEND_URL}
      # Outras variáveis
    networks:
      - taiga
    ports:
      - 9000:80
    volumes:
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    depends_on:
      taiga-back:
        condition: service_healthy
      taiga-worker:
        condition: service_healthy

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:

networks:
  taiga:
